// turbojpeg.h
namespace Carnassial.Interop
{
    internal enum LibjpegParameter
    {
        TJPARAM_STOPONWARNING,
        TJPARAM_BOTTOMUP,
        TJPARAM_NOREALLOC,
        TJPARAM_QUALITY,
        TJPARAM_SUBSAMP,
        TJPARAM_JPEGWIDTH,
        TJPARAM_JPEGHEIGHT,
        TJPARAM_PRECISION,
        TJPARAM_COLORSPACE,
        TJPARAM_FASTUPSAMPLE,
        TJPARAM_FASTDCT,
        TJPARAM_OPTIMIZE,
        TJPARAM_PROGRESSIVE,
        TJPARAM_SCANLIMIT,
        TJPARAM_ARITHMETIC,
        TJPARAM_LOSSLESS,
        TJPARAM_LOSSLESSPSV,
        TJPARAM_LOSSLESSPT,
        TJPARAM_RESTARTBLOCKS,
        TJPARAM_RESTARTROWS,
        TJPARAM_XDENSITY,
        TJPARAM_YDENSITY,
        TJPARAM_DENSITYUNITS
    }
}
