//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnassial {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class CarnassialSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CarnassialSettings defaultInstance = ((CarnassialSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CarnassialSettings())));
        
        public static CarnassialSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("carnassialdev@gmail.com")]
        public string DevTeamEmail {
            get {
                return ((string)(this["DevTeamEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CascadesCarnivoreProject/Carnassial")]
        public string GithubOrganizationAndRepo {
            get {
                return ((string)(this["GithubOrganizationAndRepo"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioFeedback {
            get {
                return ((bool)(this["AudioFeedback"]));
            }
            set {
                this["AudioFeedback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("And")]
        public string CustomSelectionTermCombiningOperator {
            get {
                return ((string)(this["CustomSelectionTermCombiningOperator"]));
            }
            set {
                this["CustomSelectionTermCombiningOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DarkLuminosityThreshold {
            get {
                return ((double)(this["DarkLuminosityThreshold"]));
            }
            set {
                this["DarkLuminosityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float DesiredImageRendersPerSecond {
            get {
                return ((float)(this["DesiredImageRendersPerSecond"]));
            }
            set {
                this["DesiredImageRendersPerSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.4")]
        public float ImageClassificationChangeSlowdown {
            get {
                return ((float)(this["ImageClassificationChangeSlowdown"]));
            }
            set {
                this["ImageClassificationChangeSlowdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MostRecentlyUsedImageSets {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MostRecentlyUsedImageSets"]));
            }
            set {
                this["MostRecentlyUsedImageSets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrderFilesByDateTime {
            get {
                return ((bool)(this["OrderFilesByDateTime"]));
            }
            set {
                this["OrderFilesByDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SkipFileClassification {
            get {
                return ((bool)(this["SkipFileClassification"]));
            }
            set {
                this["SkipFileClassification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuppressFileCountOnImportDialog {
            get {
                return ((bool)(this["SuppressFileCountOnImportDialog"]));
            }
            set {
                this["SuppressFileCountOnImportDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuppressImportPrompt {
            get {
                return ((bool)(this["SuppressImportPrompt"]));
            }
            set {
                this["SuppressImportPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float VideoSlowdown {
            get {
                return ((float)(this["VideoSlowdown"]));
            }
            set {
                this["VideoSlowdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,1343,824")]
        public string CarnassialWindowPosition {
            get {
                return ((string)(this["CarnassialWindowPosition"]));
            }
            set {
                this["CarnassialWindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("303")]
        public double ControlGridWidth {
            get {
                return ((double)(this["ControlGridWidth"]));
            }
            set {
                this["ControlGridWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-12-29")]
        public global::System.DateTime MostRecentCheckForUpdates {
            get {
                return ((global::System.DateTime)(this["MostRecentCheckForUpdates"]));
            }
            set {
                this["MostRecentCheckForUpdates"] = value;
            }
        }
    }
}
