// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.RegistryTests.EditorProductionKeysRead")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.CarnassialTest.PopulateDefaultDatabase(Carnassial.Data.FileDatabase,System.Boolean)~System.Collections.Generic.List{Carnassial.UnitTests.FileExpectations}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.LowLevelTests.UndoRedoChain")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.DatabaseTests.ClassInitialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.FileTests.ClassInitialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.LowLevelTests.ClassInitialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.UserInterfaceTests.ClassInitialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.VersionTests.ClassInitialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.DatabaseTests.HybridVideoFileIOTransactionsAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.DatabaseTests.MoveFile")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.TestConstant.FileExpectation.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.FileTests.CheckDifferenceResult(Carnassial.Images.ImageDifferenceResult,Carnassial.Images.ImageCache,Carnassial.Data.FileDatabase)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Carnassial.UnitTests.CarnassialTest.CreateFile(Carnassial.Data.FileDatabase,System.TimeZoneInfo,Carnassial.UnitTests.FileExpectations,Carnassial.Images.MetadataReadResults@)~Carnassial.Data.ImageRow")]